nohup: ignoring input
Watching for file changes with StatReloader
[28/Oct/2019 22:22:46] "GET /theaters/ HTTP/1.1" 200 202049
[28/Oct/2019 22:22:46] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:47] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:51] "GET /theaters/ HTTP/1.1" 200 202049
[28/Oct/2019 22:22:51] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:51] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:56] "GET /movies/ HTTP/1.1" 200 10713
[28/Oct/2019 22:22:56] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:59] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:22:59] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:00] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:00] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:00] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:01] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:01] "GET /theaters/ HTTP/1.1" 200 92551
[28/Oct/2019 22:23:02] "GET /theaters/ HTTP/1.1" 200 92551
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[29/Oct/2019 07:51:20] "HEAD / HTTP/1.0" 200 156
[29/Oct/2019 08:31:33] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:33] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[29/Oct/2019 08:31:34] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[29/Oct/2019 08:31:37] "GET /favicon.ico HTTP/1.1" 404 6652
[29/Oct/2019 08:42:51] "GET /theaters/ HTTP/1.1" 200 202049
[29/Oct/2019 08:42:55] "GET / HTTP/1.1" 200 5584
[29/Oct/2019 08:43:00] "GET /movies/ HTTP/1.1" 200 10713
[29/Oct/2019 08:43:09] "GET /movieschedules/ HTTP/1.1" 200 48034
[29/Oct/2019 08:47:37] "GET /theaters/ HTTP/1.1" 200 202049
[29/Oct/2019 08:55:02] "GET /movie_api/searchTheaterWithPos/?latitude=37.498241&longitude=127.026451 HTTP/1.1" 200 3356
Performing system checks...

System check identified no issues (0 silenced).
October 28, 2019 - 22:22:45
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('14.36.251.74', 60967)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('14.36.251.74', 27995)
----------------------------------------
long:37.498241, lat:127.026451, movieName:조커
megabox강남
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 95, in SearchTheaterOrderedScheduleWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    MegaBoxCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 304, in MegaBoxCrawl
    driver.get(url)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)

[29/Oct/2019 08:55:30] "GET /movie_api/searchTheaterOrderedScheduleWithPos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 99384
long:37.498241, lat:127.026451, movieName:조커
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 96, in SearchTheaterOrderedScheduleWithPos
    movieObj = Movies.objects.get(movieName=movieName)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
movies.models.Movies.DoesNotExist: Movies matching query does not exist.
[29/Oct/2019 08:55:37] "GET /movie_api/searchTheaterOrderedScheduleWithPos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 83899
long:37.498241, lat:127.026451, movieName:조커
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 96, in SearchTheaterOrderedScheduleWithPos
    movieObj = Movies.objects.get(movieName=movieName)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
movies.models.Movies.DoesNotExist: Movies matching query does not exist.
[29/Oct/2019 09:08:40] "GET /movie_api/searchTheaterOrderedScheduleWithPos/?latitude=37.498241&longitude=127.026451&movieName=%EC%A1%B0%EC%BB%A4 HTTP/1.1" 500 83898
/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 29, 2019 - 09:13:41
Django version 2.2.6, using settings 'movie_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
long:37.498241, lat:127.026451, movieName:조커
megabox강남
82년생 김지영
Internal Server Error: /movie_api/searchTheaterOrderedScheduleWithPos/
Traceback (most recent call last):
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/swim/.venv/movieapi/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/movieapi.py", line 95, in SearchTheaterOrderedScheduleWithPos
    MovieCrawl(reqtheater)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 47, in MovieCrawl
    MegaBoxCrawl(theaterObj)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/crawling.py", line 345, in MegaBoxCrawl
    movieObj = GetMovieInfo(movieNameStr)
  File "/home/swim/workspace/bixby-kuchara/webserver/movie_server_win/movie_server/movies/update.py", line 110, in GetMovieInfo
    MoviesEle = Movies(movieName=movieName, director=director, \
UnboundLocalError: local variable 'director' referenced before assignment
